In [2]:
!pip install tensorflow==2.15.0 pandas numpy scikit-learn tensorboard matplotlib streamlit

Collecting tensorflow==2.15.0
  Downloading tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting tensorboard
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp311-cp311-win_amd64.whl.metadata (52 kB)
Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Collecting tensorflow-intel==2.15.0 (from tensorflow==2.15.0)
  Downloading tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=23.5.26 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting h5py>=2.9.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading h5py-3.16.0-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting libclang>=13.0.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting ml-dtypes~=0.2.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading ml_dtypes-0.2.0-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting numpy
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow==2.15.0) (26.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading protobuf-4.25.9-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Requirement already satisfied: setuptools in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow==2.15.0) (82.0.1)
Requirement already satisfied: six>=1.12.0 in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow==2.15.0) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow==2.15.0) (4.15.0)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading wrapt-1.14.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading grpcio-1.80.0-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting tensorboard
  Downloading tensorboard-2.15.2-py3-none-any.whl.metadata (1.7 kB)
Collecting tensorflow-estimator<2.16,>=2.15.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.16,>=2.15.0 (from tensorflow-intel==2.15.0->tensorflow==2.15.0)
  Downloading keras-2.15.0-py3-none-any.whl.metadata (2.4 kB)
Collecting google-auth<3,>=1.6.3 (from tensorboard)
  Downloading google_auth-2.52.0-py3-none-any.whl.metadata (5.5 kB)
Collecting google-auth-oauthlib<2,>=0.5 (from tensorboard)
  Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting markdown>=2.6.8 (from tensorboard)
  Downloading markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Collecting requests<3,>=2.21.0 (from tensorboard)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth<3,>=1.6.3->tensorboard)
  Downloading cryptography-48.0.0-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<2,>=0.5->tensorboard)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorboard)
  Downloading charset_normalizer-3.4.7-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorboard)
  Downloading idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.21.0->tensorboard)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.21.0->tensorboard)
  Downloading certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp311-cp311-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.1.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.1.1-py3-none-any.whl.metadata (5.8 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting starlette>=0.40.0 (from streamlit)
  Downloading starlette-1.0.0-py3-none-any.whl.metadata (6.3 kB)
Collecting uvicorn>=0.30.0 (from streamlit)
  Downloading uvicorn-0.46.0-py3-none-any.whl.metadata (6.7 kB)
Collecting httptools>=0.6.3 (from streamlit)
  Downloading httptools-0.7.1-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting anyio>=4.0.0 (from streamlit)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting python-multipart>=0.0.10 (from streamlit)
  Downloading python_multipart-0.0.28-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets>=12.0.0 (from streamlit)
  Downloading websockets-16.0-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Collecting itsdangerous>=2.1.2 (from streamlit)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=2.4.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.21.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: colorama in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0->tensorflow==2.15.0) (0.46.3)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard)
  Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-0.30.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard)
  Downloading pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Collecting h11>=0.8 (from uvicorn>=0.30.0->streamlit)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading tensorflow-2.15.0-cp311-cp311-win_amd64.whl (2.1 kB)
Downloading tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl (300.9 MB)
   ---------------------------------------- 0.0/300.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/300.9 MB ? eta -:--:--
   ---------------------------------------- 0.8/300.9 MB 2.0 MB/s eta 0:02:33
   ---------------------------------------- 1.3/300.9 MB 2.2 MB/s eta 0:02:19
   ---------------------------------------- 1.8/300.9 MB 2.2 MB/s eta 0:02:17
   ---------------------------------------- 2.1/300.9 MB 2.2 MB/s eta 0:02:18
   ---------------------------------------- 2.6/300.9 MB 2.2 MB/s eta 0:02:17
   ---------------------------------------- 3.1/300.9 MB 2.2 MB/s eta 0:02:14
   ---------------------------------------- 3.7/300.9 MB 2.2 MB/s eta 0:02:13
    --------------------------------------- 4.5/300.9 MB 2.3 MB/s eta 0:02:09
    --------------------------------------- 5.0/300.9 MB 2.3 MB/s eta 0:02:07
    --------------------------------------- 5.5/300.9 MB 2.4 MB/s eta 0:02:06
    --------------------------------------- 6.0/300.9 MB 2.4 MB/s eta 0:02:04
    --------------------------------------- 6.8/300.9 MB 2.4 MB/s eta 0:02:01
    --------------------------------------- 7.3/300.9 MB 2.4 MB/s eta 0:02:00
   - -------------------------------------- 7.9/300.9 MB 2.4 MB/s eta 0:02:00
   - -------------------------------------- 8.7/300.9 MB 2.5 MB/s eta 0:01:58
   - -------------------------------------- 9.2/300.9 MB 2.5 MB/s eta 0:01:56
   - -------------------------------------- 10.0/300.9 MB 2.6 MB/s eta 0:01:53
   - -------------------------------------- 10.7/300.9 MB 2.6 MB/s eta 0:01:52
   - -------------------------------------- 11.3/300.9 MB 2.6 MB/s eta 0:01:51
   - -------------------------------------- 12.1/300.9 MB 2.7 MB/s eta 0:01:49
   - -------------------------------------- 12.6/300.9 MB 2.7 MB/s eta 0:01:48
   - -------------------------------------- 13.4/300.9 MB 2.7 MB/s eta 0:01:46
   - -------------------------------------- 14.4/300.9 MB 2.8 MB/s eta 0:01:44
   -- ------------------------------------- 15.2/300.9 MB 2.8 MB/s eta 0:01:42
   -- ------------------------------------- 16.0/300.9 MB 2.8 MB/s eta 0:01:41
   -- ------------------------------------- 16.8/300.9 MB 2.9 MB/s eta 0:01:39
   -- ------------------------------------- 17.6/300.9 MB 2.9 MB/s eta 0:01:38
   -- ------------------------------------- 18.1/300.9 MB 2.9 MB/s eta 0:01:38
   -- ------------------------------------- 19.1/300.9 MB 2.9 MB/s eta 0:01:36
   -- ------------------------------------- 19.9/300.9 MB 3.0 MB/s eta 0:01:35
   -- ------------------------------------- 21.0/300.9 MB 3.0 MB/s eta 0:01:33
   -- ------------------------------------- 22.0/300.9 MB 3.1 MB/s eta 0:01:31
   --- ------------------------------------ 22.8/300.9 MB 3.1 MB/s eta 0:01:31
   --- ------------------------------------ 23.3/300.9 MB 3.1 MB/s eta 0:01:30
   --- ------------------------------------ 24.1/300.9 MB 3.1 MB/s eta 0:01:30
   --- ------------------------------------ 24.9/300.9 MB 3.1 MB/s eta 0:01:29
   --- ------------------------------------ 25.7/300.9 MB 3.1 MB/s eta 0:01:28
   --- ------------------------------------ 26.5/300.9 MB 3.2 MB/s eta 0:01:28
   --- ------------------------------------ 27.5/300.9 MB 3.2 MB/s eta 0:01:27
   --- ------------------------------------ 28.3/300.9 MB 3.2 MB/s eta 0:01:26
   --- ------------------------------------ 29.1/300.9 MB 3.2 MB/s eta 0:01:25
   --- ------------------------------------ 29.9/300.9 MB 3.2 MB/s eta 0:01:25
   ---- ----------------------------------- 30.9/300.9 MB 3.2 MB/s eta 0:01:24
   ---- ----------------------------------- 31.7/300.9 MB 3.3 MB/s eta 0:01:23
   ---- ----------------------------------- 32.8/300.9 MB 3.3 MB/s eta 0:01:22
   ---- ----------------------------------- 33.8/300.9 MB 3.3 MB/s eta 0:01:21
   ---- ----------------------------------- 34.6/300.9 MB 3.3 MB/s eta 0:01:20
   ---- ----------------------------------- 35.1/300.9 MB 3.3 MB/s eta 0:01:21
   ---- ----------------------------------- 35.9/300.9 MB 3.3 MB/s eta 0:01:20
   ---- ----------------------------------- 36.2/300.9 MB 3.3 MB/s eta 0:01:21
   ---- ----------------------------------- 36.7/300.9 MB 3.3 MB/s eta 0:01:21
   ---- ----------------------------------- 37.0/300.9 MB 3.3 MB/s eta 0:01:22
   ---- ----------------------------------- 37.5/300.9 MB 3.2 MB/s eta 0:01:23
   ----- ---------------------------------- 37.7/300.9 MB 3.2 MB/s eta 0:01:23
   ----- ---------------------------------- 38.0/300.9 MB 3.2 MB/s eta 0:01:24
   ----- ---------------------------------- 38.5/300.9 MB 3.1 MB/s eta 0:01:25
   ----- ---------------------------------- 38.8/300.9 MB 3.1 MB/s eta 0:01:25
   ----- ---------------------------------- 38.8/300.9 MB 3.1 MB/s eta 0:01:25
   ----- ---------------------------------- 39.1/300.9 MB 3.0 MB/s eta 0:01:27
   ----- ---------------------------------- 39.3/300.9 MB 3.0 MB/s eta 0:01:28
   ----- ---------------------------------- 39.6/300.9 MB 2.9 MB/s eta 0:01:29
   ----- ---------------------------------- 39.8/300.9 MB 2.9 MB/s eta 0:01:30
   ----- ---------------------------------- 40.1/300.9 MB 2.9 MB/s eta 0:01:30
   ----- ---------------------------------- 40.6/300.9 MB 2.9 MB/s eta 0:01:31
   ----- ---------------------------------- 40.9/300.9 MB 2.9 MB/s eta 0:01:31
   ----- ---------------------------------- 41.4/300.9 MB 2.9 MB/s eta 0:01:31
   ----- ---------------------------------- 41.9/300.9 MB 2.8 MB/s eta 0:01:32
   ----- ---------------------------------- 42.2/300.9 MB 2.8 MB/s eta 0:01:32
   ----- ---------------------------------- 42.7/300.9 MB 2.8 MB/s eta 0:01:32
   ----- ---------------------------------- 43.3/300.9 MB 2.8 MB/s eta 0:01:32
   ----- ---------------------------------- 43.8/300.9 MB 2.8 MB/s eta 0:01:32
   ----- ---------------------------------- 44.3/300.9 MB 2.8 MB/s eta 0:01:32
   ----- ---------------------------------- 44.8/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 45.4/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 45.9/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 46.4/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 46.9/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 47.4/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 48.2/300.9 MB 2.8 MB/s eta 0:01:32
   ------ --------------------------------- 48.8/300.9 MB 2.8 MB/s eta 0:01:31
   ------ --------------------------------- 49.5/300.9 MB 2.8 MB/s eta 0:01:31
   ------ --------------------------------- 50.3/300.9 MB 2.8 MB/s eta 0:01:30
   ------ --------------------------------- 50.9/300.9 MB 2.8 MB/s eta 0:01:30
   ------ --------------------------------- 51.6/300.9 MB 2.8 MB/s eta 0:01:30
   ------ --------------------------------- 52.4/300.9 MB 2.8 MB/s eta 0:01:29
   ------- -------------------------------- 53.5/300.9 MB 2.8 MB/s eta 0:01:28
   ------- -------------------------------- 54.3/300.9 MB 2.8 MB/s eta 0:01:28
   ------- -------------------------------- 55.1/300.9 MB 2.8 MB/s eta 0:01:27
   ------- -------------------------------- 55.8/300.9 MB 2.9 MB/s eta 0:01:26
   ------- -------------------------------- 56.9/300.9 MB 2.9 MB/s eta 0:01:25
   ------- -------------------------------- 57.7/300.9 MB 2.9 MB/s eta 0:01:25
   ------- -------------------------------- 58.5/300.9 MB 2.9 MB/s eta 0:01:24
   ------- -------------------------------- 59.2/300.9 MB 2.9 MB/s eta 0:01:24
   -------- ------------------------------- 60.3/300.9 MB 2.9 MB/s eta 0:01:23
   -------- ------------------------------- 61.3/300.9 MB 2.9 MB/s eta 0:01:22
   -------- ------------------------------- 62.4/300.9 MB 3.0 MB/s eta 0:01:21
   -------- ------------------------------- 63.4/300.9 MB 3.0 MB/s eta 0:01:20
   -------- ------------------------------- 64.5/300.9 MB 3.0 MB/s eta 0:01:19
   -------- ------------------------------- 65.5/300.9 MB 3.0 MB/s eta 0:01:19
   -------- ------------------------------- 66.6/300.9 MB 3.0 MB/s eta 0:01:18

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /packages/d8/1a/3ca2293d8552bacea3e67e9600d2d1df7df4a325059769ad83d91c279595/streamlit-1.57.0-py3-none-any.whl.metadata

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [4]:
df=pd.read_csv("Churn_Modelling.csv")

In [5]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df=df.drop(['RowNumber',	'CustomerId',	'Surname'], axis=1)

In [7]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:
#Encode categorical variables
label_encoder=LabelEncoder()
df['Gender']=label_encoder.fit_transform(df['Gender'])

In [14]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [18]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
geo_encoder=ohe.fit_transform(df[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [19]:
ohe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [21]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(), columns=ohe.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [ ]:
#Combine One hot encoded part with original data

In [23]:
df=pd.concat([df.drop('Geography', axis=1),geo_encoded_df],axis=1)

In [24]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [28]:
#Save the scaler and encoder
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(ohe, file)

In [29]:
X=df.drop('Exited', axis=1)
y=df['Exited']

#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
#Scaling the features
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [31]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Implmention

In [40]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [35]:
import datetime

In [38]:
(X_train.shape[1],)

(12,)

In [41]:
#Building the ANN model
model=Sequential([
    Dense(64,activation='relu', input_shape=(X_train.shape[1],)), # HL1 with 64 neurons and ReLU activation
    Dense(32,activation='relu'), # HL2 with 32 neurons and ReLU activation
    Dense(1, activation='sigmoid') # Output layer with 1 neuron and sigmoid activation for binary classification
])

WARNING:tensorflow:From c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [42]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [43]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [44]:
#To do bacckpropagation and update weights, we need to compile the model with an optimizer and a loss function
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [71]:
## Set up TensorBoard callback, this will save logs for visualization in TensorBoard
# What is happening here is that we are creating a log directory with a timestamp to store the logs for this training session. The TensorBoard callback will write logs to this directory during training, which can then be visualized using TensorBoard.
# What is call log is a directory where TensorBoard will save logs related to the training process, such as loss and accuracy metrics, histograms of weights, and other relevant information. The log_dir variable is created by concatenating a base directory ('logs/fit') with a timestamp generated using datetime.datetime.now().strftime('%Y%m%d-%H%M%S'). This ensures that each training session's logs are stored in a unique directory based on the date and time of the training.

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir='logs/fit/' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [72]:
# Setting up EarlyStopping callback to monitor validation loss and stop training if it doesn't improve for 5 consecutive epochs. This helps prevent overfitting and saves time by stopping training when the model has stopped improving on the validation set.
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [73]:
#Training the model with the training data, using a batch size of 32 and training for a maximum of 100 epochs. The validation data is set to the test set, and we are using the early stopping and TensorBoard callbacks to monitor the training process and prevent overfitting.
#Batch size is the number of samples that will be propagated through the network at once. After each batch, the model's weights are updated based on the loss calculated from that batch. This allows for more efficient training and can help with convergence.
history=model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorflow_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3060 - accuracy: 0.8700 - val_loss: 0.3774 - val_accuracy: 0.8520
Epoch 2/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3046 - accuracy: 0.8724 - val_loss: 0.3613 - val_accuracy: 0.8550
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3062 - accuracy: 0.8698 - val_loss: 0.3610 - val_accuracy: 0.8550
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3015 - accuracy: 0.8699 - val_loss: 0.3511 - val_accuracy: 0.8555
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3024 - accuracy: 0.8696 - val_loss: 0.3674 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3001 - accuracy: 0.8744 - val_loss: 0.3773 - val_accuracy: 0.8545
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2935 - accuracy: 0.8751 - val_loss: 0.3645 - val_accuracy: 0.8620
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2955 - accuracy: 0.8723 - val_loss: 0.3796 - val_accuracy: 0.8520
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2959 - accuracy: 0.8719 - val_loss: 0.3745 - val_accuracy: 0.8515
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 0.2904 - accuracy: 0.8760 - val_loss: 0.3769 - val_accuracy: 0.8565
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2919 - accuracy: 0.8754 - val_loss: 0.3663 - val_accuracy: 0.8560
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2876 - accuracy: 0.8741 - val_loss: 0.3748 - val_accuracy: 0.8520
Epoch 13/100
250/250 [==============================] - 2s 6ms/step - loss: 0.2865 - accuracy: 0.8756 - val_loss: 0.3878 - val_accuracy: 0.8530
Epoch 14/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2850 - accuracy: 0.8755 - val_loss: 0.3867 - val_accuracy: 0.8515

In [74]:
#Save the trained model
model.save('churn_model.h5')

c:\Users\jaisw\Desktop\Projects\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [75]:
#Load TensorBoard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [76]:
%tensorboard --logdir logs/fit20260510-212529

Reusing TensorBoard on port 6008 (pid 16352), started 0:04:32 ago. (Use '!kill 16352' to kill it.)

In [77]:
#Load the picle file and trained model
import pickle


model=load_model('churn_model.h5')

#Load the scaler and encoders
with open('scaler.pkl', 'rb') as file:
    scaler=pickle.load(file)
with open('encoders.pkl', 'rb') as file:
    encoders=pickle.load(file)
with open('ohe.pkl', 'rb') as file:
    ohe=pickle.load(file)

NameError: name 'load_model' is not defined

In [ ]:
from tensorflow.keras.models import load_model

model = load_model('churn_model.h5')

# Load the scaler and encoders with correct file names
with open('scaler.pkl', 'rb') as file:
	scaler = pickle.load(file)
with open('label_encoder_gender.pkl', 'rb') as file:
	label_encoder = pickle.load(file)
with open('onehot_encoder_geo.pkl', 'rb') as file:
	ohe = pickle.load(file)